# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - rm -rf manpages
    - mkdir manpages
    - sh -c 'go run . completion "bash" >./completions/{{ .ProjectName }}.bash'
    - sh -c 'go run . completion "zsh" >./completions/{{ .ProjectName }}.zsh'
    - sh -c 'go run . completion "fish" >./completions/{{ .ProjectName }}.fish'
    - sh -c 'go run . man | gzip -c >./manpages/{{ .ProjectName }}.1.gz'

git:
  tag_sort: -version:creatordate

gomod:
  proxy: true

builds:
  - binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    main: "."
    ldflags: -s -w -X github.com/DanStough/epok/internal/buildinfo.gitCommit={{ .ShortCommit }}{{ if .IsGitDirty }}{{ .GitTreeState }}{{ end }} -X github.com/DanStough/epok/internal/buildinfo.version={{ .Tag }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarm: "7"

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    wrap_in_directory: true
    files:
      - README*
      - LICENSE*
      - manpages/*
      - completions/*

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  groups:
    - title: Dependency updates
      regexp: "^.*\\(deps\\)*:+.*$"
      order: 300
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

homebrew_casks:
  - repository:
      owner: DanStough
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "Dan Stough"
      email: "daniel.stough@gmail.com"
    homepage: "https://github.com/DanStough/epok"
    description: "A CLI for working with Unix Timestamps & Timezones"
    manpages:
      - "manpages/{{ .ProjectName }}.1.gz"
    completions:
      bash: "completions/{{ .ProjectName }}.bash"
      zsh: "completions/{{ .ProjectName }}.zsh"
      fish: "completions/{{ .ProjectName }}.fish"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/{{ .ProjectName }}"]
          end
